---
plugins:
    markdownlint:
        enabled: true
    editorconfig:
        enabled: true
    sonar-java:
        enabled: true
    test: some very very very very very very very very very very very very very very very very long line
